name: build gh-pages
on:
  push:
    branches:
      - main

jobs:
  build_html:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Python dependencies
        run: |
          pip3 install --user setuptools wheel
          pip3 install --user svdtools
      - name: Put pip binary directory into path
        run: echo "~/.local/bin" >> $GITHUB_PATH
      - name: Build HTML
        run: |
          make -j2 html
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
          force_orphan: true
