name: build mmaps

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build mmaps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gd32-rs
        uses: actions/checkout@v3
        with:
          path: gd32-rs
      - name: Checkout mmaps
        uses: actions/checkout@v3
        with:
          repository: gd32-rust/gd32-rs-mmaps
          ssh-key: ${{ secrets.MMAPS_KEY }}
          path: gd32-rs-mmaps
      - name: Install Python dependencies
        run: |
          pip3 install --user setuptools wheel
          pip3 install --user svdtools
      - name: Put pip binary directory into path
        run: echo "~/.local/bin" >> $GITHUB_PATH
      - name: Build and publish
        run: |
          cd gd32-rs
          COMMIT=$(git rev-parse HEAD)
          make -j2 mmaps
          mv mmaps/* ../gd32-rs-mmaps/
          cd ../gd32-rs-mmaps
          git config user.name "gd32-rs builder"
          git config user.email "action@github.com"
          git add .
          git commit --allow-empty -m "gd32-rs main $COMMIT"
          git push origin main
